---
- name: Test Playbook
  hosts: "{{ server_list }}"
  gather_facts: no
  tasks:
    - name: Debug http_port
      debug:
        msg: "HTTP Port: {{ http_port }}"
    - name: Debug max_clients
      debug:
        msg: "Max Clients: {{ max_clients }}"
    - name: Debug localhost
      debug:
        msg: "Max Clients: {{ server_list }}"

